[build]
builder = "nixpacks"

[phases.setup]
nixpkgs = [
  "python312Full",
  "pip",
  "setuptools",
  "wheel",
  "cython",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn flask_server:app"