[build]
builder = "nixpacks"

[phases.setup]
nixpkgs = [
  "python310",  # Pakai Python 3.10
  "python310Packages.pip",  # Jangan lupa pip-nya
  "gcc",  # Buat compile package yang butuh kompilasi
  "pkg-config"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",  # Pakai python -m pip
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn flask_server:app"