[build]
builder = "nixpacks"

[phases.setup]
nixpkgs = [
  "python310Full",           # Python 3.10 lebih aman dari 3.12
  "python310Packages.distutils",
  "pip",
  "setuptools",
  "wheel",
  "cython",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn flask_server:app"