[build]
builder = "nixpacks"

[phases.setup]
nixpkgs = [
  # Pakai python3 (auto pilih versi stabil terbaru)
  "python3",  
  "python3Packages.pip",
  "python3Packages.setuptools",
  "python3Packages.virtualenv",
  "gcc",
  "pkg-config"
]

[phases.install]
cmds = [
  # Buat virtual environment dulu
  "python -m venv /opt/venv",
  # Aktifin venv
  ". /opt/venv/bin/activate",
  # Install dependencies
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn flask_server:app"